### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alexkoven** [ulyantsev/EFSM-tools#4]
Hey,

The repo doesn't have a license yet. Could you add one?

**Comment by igor-buzhinsky** [comment]
@Jackiemesser Good point, but, if I remember correctly, the rights to some parts of this code were transferred to a former employer of the authors, so some negotiations are likely needed, for which at least I won't find time. @ulyantsev What do you think?

**Comment by ulyantsev** [comment]
Yep. Any commercial usage should be discussed separately, the code is registered as an IP of the authors and ITMO University. Any non-profit usage is permitted as long as they give you credit.
